# 1. Import dependencies

In [11]:
!python -m pip install --quiet -r ../requirements.txt

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [12]:
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder,
    OrdinalEncoder,
    StandardScaler,
)

from churn_prediction.paths import PROCESSED_DATA_PATH

In [13]:
df = pd.read_csv(PROCESSED_DATA_PATH)

X = df.drop(
    columns=['customerID', 'Churn']
)
y = df['Churn']

# 2. Split train, validation và test

## Split train + validation với test

In [14]:
X_dev, X_test, y_dev, y_test = train_test_split(
    X,
    y, 
    test_size=0.2,
    random_state=69,
    stratify=y,
)

## Split train với validation

In [15]:
X_train, X_val, y_train, y_val = train_test_split(
    X_dev,
    y_dev,
    test_size=0.2,
    random_state=67,
    stratify=y_dev,
)

## Kiểm tra

In [16]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

print(y_train.value_counts(normalize=True))
print(y_val.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

(4507, 19)
(1127, 19)
(1409, 19)
Churn
No     0.734635
Yes    0.265365
Name: proportion, dtype: float64
Churn
No     0.734694
Yes    0.265306
Name: proportion, dtype: float64
Churn
No     0.734564
Yes    0.265436
Name: proportion, dtype: float64

# 3. Preprocessing

## Định nghĩa các cột

In [17]:
numerical_features = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]
yes_no_features = [
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling"
]
binary_features = [
    "SeniorCitizen",
    *yes_no_features
]
multiclass_features = [
    "gender",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]

## Kiểm tra

In [18]:
all_features = (
    numerical_features
    + binary_features
    + multiclass_features
)
assert len(all_features) == len(set(all_features))
assert set(all_features) == set(X.columns)

## Binary Transformer

In [19]:
binary_transformer = OrdinalEncoder(
    categories=[
        ["No", "Yes"]
        for _ in yes_no_features
    ]
)

## ColumnTransformer

In [20]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features,
        ),
        (
            "binary",
            binary_transformer,
            yes_no_features,
        ),
        (
            "senior",
            "passthrough",
            ["SeniorCitizen"],
        ),
        (
            "multi",
            OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=False,
            ),
            multiclass_features,
        )
    ],
    remainder="drop",
)

## Nhìn thử Output

In [24]:
preprocessor.set_output(
    transform="pandas"
)

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['tenure', 'MonthlyCharges', 'TotalCharges']),
                                ('binary',
                                 OrdinalEncoder(categories=[['No', 'Yes'],
                                                            ['No', 'Yes'],
                                                            ['No', 'Yes'],
                                                            ['No', 'Yes']]),
                                 ['Partner', 'Dependents', 'PhoneService',
                                  'PaperlessBilling']),
                                ('senior', 'passthrough', ['SeniorCitizen']),
                                ('multi',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['gender', 'MultipleLines', 'InternetService',
                                  'OnlineSecurity', 'OnlineBackup',
                                  'DeviceProtection', 'TechSupport',
                                  'StreamingTV', 'StreamingMovies', 'Contract',
                                  'PaymentMethod'])])

In [25]:
X_train_transformed = preprocessor.fit_transform(
    X_train
)

### Kiểm tra

In [26]:
print(X_train.shape)
print(X_train_transformed.shape)

(4507, 19)
(4507, 41)

## Lấy tên cột trong Transformer

In [28]:
X_train_transformed.head()

,num__tenure,num__MonthlyCharges,num__TotalCharges,binary__Partner,binary__Dependents,binary__PhoneService,binary__PaperlessBilling,senior__SeniorCitizen,multi__gender_Female,multi__gender_Male,...,multi__StreamingMovies_No,multi__StreamingMovies_No internet service,multi__StreamingMovies_Yes,multi__Contract_Month-to-month,multi__Contract_One year,multi__Contract_Two year,multi__PaymentMethod_Bank transfer (automatic),multi__PaymentMethod_Credit card (automatic),multi__PaymentMethod_Electronic check,multi__PaymentMethod_Mailed check
5381,-0.022491,0.468439,0.071530,1.0,0.0,1.0,1.0,0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3251,0.180489,1.386233,0.779054,0.0,0.0,1.0,1.0,1,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3142,-1.280967,-1.479195,-0.996332,0.0,0.0,1.0,0.0,0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
493,1.154793,-0.020941,0.711261,1.0,0.0,1.0,0.0,1,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3853,0.545853,0.267414,0.423994,0.0,0.0,1.0,0.0,0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

### Check numerical

In [30]:
X_train_transformed[
    [
        "num__tenure",
        "num__MonthlyCharges",
        "num__TotalCharges"
    ]
].describe()

        num__tenure  num__MonthlyCharges  num__TotalCharges
count  4.507000e+03         4.507000e+03       4.507000e+03
mean  -5.044901e-17         1.142985e-16       9.301536e-17
std    1.000111e+00         1.000111e+00       1.000111e+00
min   -1.321563e+00        -1.530275e+00      -1.005039e+00
25%   -9.561993e-01        -9.856958e-01      -8.294118e-01
50%   -1.442793e-01         1.800835e-01      -3.907053e-01
75%    9.518127e-01         8.358858e-01       6.548150e-01
max    1.601349e+00         1.778396e+00       2.814396e+00

# 4. Pipline

## Tạo pipeline

In [31]:
pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor,
        ),
        (
            "model",
            LogisticRegression(
                max_iter=1000,
            ),
        ),
    ]
)

## Fit với train

In [32]:
pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('binary',
                                                  OrdinalEncoder(categories=[['No',
                                                                              'Yes'],
                                                                             ['No',
                                                                              'Yes'],
                                                                             ['No',
                                                                              'Yes'],
                                                                             ['No',
                                                                              'Yes']]),
                                                  ['Partner', 'Dependents',
                                                   'PhoneService',
                                                   'PaperlessBilling']),
                                                 ('senior', 'passthrough',
                                                  ['SeniorCitizen']),
                                                 ('multi',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['gender', 'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000))])

## Validation

### Thử với threshold mặc định $0.5$

In [33]:
y_val_pred = pipeline.predict(
    X_val
)

y_val_prob_yes = pipeline.predict_proba(
    X_val
)[:, 1]

### Tính metrics

In [34]:
val_accuracy = accuracy_score(
    y_val,
    y_val_pred,
)

val_precision = precision_score(
    y_val,
    y_val_pred,
    pos_label="Yes",
)

val_recall = recall_score(
    y_val,
    y_val_pred,
    pos_label="Yes",
)

val_f1 = f1_score(
    y_val,
    y_val_pred,
    pos_label="Yes",
)

val_roc_auc = roc_auc_score(
    y_val,
    y_val_prob_yes,
)

val_ap = average_precision_score(
    y_val,
    y_val_prob_yes,
    pos_label="Yes",
)

In [35]:
print(f"Accuracy:          {val_accuracy:.4f}")
print(f"Precision (Yes):   {val_precision:.4f}")
print(f"Recall (Yes):      {val_recall:.4f}")
print(f"F1 (Yes):          {val_f1:.4f}")
print(f"ROC-AUC:           {val_roc_auc:.4f}")
print(f"Average Precision: {val_ap:.4f}")

Accuracy:          0.8110
Precision (Yes):   0.6641
Recall (Yes):      0.5819
F1 (Yes):          0.6203
ROC-AUC:           0.8500
Average Precision: 0.6690

Giống hệt với làm thủ công

Vì vậy, `Manual preprocessing` $\approx$ `ColumnTransformer preprocessing`

### Với threshold $0.37$

In [37]:
selected_threshold = 0.37

In [38]:
y_val_prob_yes = pipeline.predict_proba(
    X_val
)[:, 1]

y_val_pred_threshold = np.where(
    y_val_prob_yes >= selected_threshold,
    "Yes",
    "No",
)

### Tính F1

In [40]:
print(
    f1_score(
        y_val,
        y_val_pred_threshold,
        pos_label="Yes",
    )
)

0.6511627906976745

Khớp với validation của [04_proper_evaluation](./04_proper_evaluation.ipynb)